### ISSUE TITLE
Are you planning on migrating it to null-safety?

### ISSUE THREAD

**Issue by ketanchoyal** [Tkko/Flutter_dismissible_page#1]

**Comment by aytunch** [comment]
@Tkko Package looks promising, are you planning on maintaining it or at least upgrade to null safety?

**Comment by aytunch** [comment]
I think one of the forks handles null safety:

https://github.com/fajarcahyoprabowo/Flutter_dismissible_page

Thanks Fajar:)

**Comment by Tkko** [comment]
Migrated.
