### ISSUE TITLE
Add callback to report on drag progress

### ISSUE THREAD

**Issue by cachapa** [Tkko/Flutter_dismissible_page#10]
We're trying to fade out the page background (which is separate from the DismissiblePage widget) when the user starts dragging, but unfortunately there's no way to get the drag progress.

It would be nice if the drag progress could be reported via a callback, ideally with a value of 0.0-1.0, indicating how much the dismissible has been dragged compared to its total width/height.

**Comment by Tkko** [comment]
Sure, will do.

**Comment by aytunch** [comment]
Maybe exposing the `Rect` can be more useful than a double value for other use cases as well.

**Comment by Tkko** [comment]
Convinced, Thanks.

**Comment by Tkko** [comment]
Hey guys, long time no see, check out the new version [0.7.3](https://pub.dev/packages/dismissible_page) onDragUpdate outputs `DismissiblePageDragUpdateDetails` 
```
  final double overallDragValue;
  final double radius;
  final double opacity;
  final double scale;
  final Offset offset;
```
