### ISSUE TITLE
When `backgroundColor` is set as `Colors.transparent`, transition has grey/black color

### ISSUE THREAD

**Issue by aytunch** [Tkko/Flutter_dismissible_page#12]
I think this happens from the fact that `Colors.transparent.withOpacity(value)` creates a grey shade even if the base color is transparent.

Both in Single and Multi axis transitions we need to add a condition for `backgroundColor` being `Colors.transparent` and do not add `withOpacity` in those cases

https://github.com/Tkko/Flutter_dismissible_page/blob/c8ddb543e3c3280641b045e5fea08c8848f210a0/lib/src/multi_axis_dismissible_page.dart#L171
https://github.com/Tkko/Flutter_dismissible_page/blob/c8ddb543e3c3280641b045e5fea08c8848f210a0/lib/src/single_axis_dismissible_page.dart#L269

**Comment by aytunch** [comment]
You can see the grey overlay in the video.
This might not be about this package but if the keyboard is open, the hero animation has a weird effect (it starts stretched in width. Do you have any idea on this?)
https://user-images.githubusercontent.com/6442915/160652666-e5650610-24bb-463d-9be1-82ac8d034cf2.mov

**Comment by Tkko** [comment]
@aytunch Can you check if Image has the same problem as Video?

**Comment by Tkko** [comment]
Added  background color check in version 0.7.1
```
        final backgroundColor = widget.backgroundColor == Colors.transparent
            ? Colors.transparent
            : widget.backgroundColor.withOpacity(details.opacity);
```

**Comment by aytunch** [comment]
@Tkko the new version works perfect with the transparent background. Much smoother.
Thank you very much.

https://user-images.githubusercontent.com/6442915/161397748-ac97127d-851c-4d09-907d-3077ea64b691.mov

**Comment by HongZhiQing** [comment]
> [@Tkko](https://github.com/Tkko) the new version works perfect with the transparent background. Much smoother. Thank you very much.
> 
>  RPReplay_Final1648926324.mov

Hi Aytunch, the transition animation of the video window when pushing from page A to page B in the video is absolutely amazing. Could you please tell me how you achieved it?

**Comment by aytunch** [comment]
Hi @HongZhiQing 
I used this awesome package :)
Its been a long time, but if you are asking for the video playback not being interrupted while screen transition, iirc i did it by supplying the same video controller object to the video players in both of the pages.
