### ISSUE TITLE
It looks like you have disabled onDragUpdate

### ISSUE THREAD

**Issue by wwwhttpru** [Tkko/Flutter_dismissible_page#15]
I found that in the published version, you have commented out the code in the pub.

v0.7.2

![image](https://user-images.githubusercontent.com/56841516/172826679-313ccb83-881d-4cd7-b6a6-14a7009f4119.png)

**Comment by wwwhttpru** [comment]
onDragStart/onDragEnd don't have an implementation either.

**Comment by Tkko** [comment]
Hi @wwwhttpru, I'll fix it ASAP.

**Comment by wwwhttpru** [comment]
Thx!

**Comment by wwwhttpru** [comment]
Hello @Tkko, I hope you haven't forgotten :)

**Comment by Tkko** [comment]
> Hello @Tkko, I hope you haven't forgotten :)

Not at all, it's hard to find free time in sunny days 😄
