### ISSUE TITLE
hero --- How does make the original picture also display？

### ISSUE THREAD

**Issue by Junesui** [Tkko/Flutter_dismissible_page#17]
dismissible_page .thank you。

How does make the original picture also display？

![image](https://user-images.githubusercontent.com/53398033/188637965-6a38161e-c668-4558-b6d0-9b8c47d5eb97.png)

**Comment by aytunch** [comment]
@Junesui can you share your code please so you can get better help?

**Comment by Junesui** [comment]
@aytunch 

HI aytunch 

The above  picture is from the live demo.
 original picture is not show.

![image](https://user-images.githubusercontent.com/53398033/188641605-fce6afbb-844a-41b2-8e54-033f585cc3de.png)

**Comment by Tkko** [comment]
@Junesui  Add this to Hero widget and it will work
`      placeholderBuilder: (_,__, Widget child ) => child,`
