### ISSUE TITLE
Support both vertical and horizontal gestures at the same time

### ISSUE THREAD

**Issue by aytunch** [Tkko/Flutter_dismissible_page#2]
Instagram Stories allow you to move the page along both directions. Can we have the same too? Thanks

**Comment by Tkko** [comment]
> Thank you very much.
> 
> 
> 
> > Note that scrollable widget inside DismissiblePage might limit the functionality.
> 
> > If scroll direction matches DismissiblePage direction
> 
> 
> 
> What Instagram does is, if the scrolling widgets scroll position is not on the start position, swipe gestures keeps on scrolling the inner scroll.
> 
> If the scroll position is on start, then the page dismiss happens.
> 
> I want to try to achieve this, I know it is not the responsibility of this package but it is a common use-case.
> 
> Do you have any suggestions on how this could be done @Tkko ?
> 
> Btw I hope all you people are safe and this nonsense ends soon.

I'd love to implement that functionality as well, Airbnb app does it perfectly. If you manage to replicate it please let me know.

DraggableDismissibleSheet is doing kinda similar thing for reference.

Thank you for asking, I'm safe for now, well, until Putin decides to occupy Georgia (my country) again 😡

**Comment by aytunch** [comment]
Do you mean `DraggableScrollableSheet`?
I could not find any info on `DraggableDismissibleSheet`?

**Comment by Tkko** [comment]
> Do you mean `DraggableScrollableSheet`?
> 
> I could not find any info on `DraggableDismissibleSheet`?

Ahh Yes, it's DraggableScrollableSheet.
