### ISSUE TITLE
Bug with PageView

### ISSUE THREAD

**Issue by gidrokolbaska** [Tkko/Flutter_dismissible_page#26]
If you dismiss the fullscreen view while pageview is still animating, you will see the double Hero effect:

https://user-images.githubusercontent.com/54116985/235725059-a2561ad2-4bc6-4c99-b96f-99bd08af337e.mov

Is it a bug or intended?

**Comment by Tkko** [comment]
This happens because both `Hero` widget is active and visible, you can listen to `PageView` and disable one of them by using `HeroMode` widget

**Comment by gidrokolbaska** [comment]
> This happens because both `Hero` widget is active and visible, you can listen to `PageView` and disable one of them by using `HeroMode` widget

Ahaa, got it. Thanks for the tip with HeroMode
