### ISSUE TITLE
Changing DismissiblePageDimissDirection resets scrollview position

### ISSUE THREAD

**Issue by brvm** [Tkko/Flutter_dismissible_page#30]
When using states to change the `DimissiblePageDismissDirection` with a `CustomScrollView` as child, change the direction to `multi` or `down`, resets the scrollposition to of the `CustomScrollView` to the top. This does not seem to happen when switching between `horizontal` and `vertical`.

**To Reproduce**
1. Create a `DimissiblePage` with a `CustomScrollView` as child
2. Use a listener or event that calls `setState()` to change the `DismissiblePageDismissDirection`
3. When switching to direction `multi` or `down`, the scroll position resets back to the top.
4. No error is printed

**DismissiblePage version:** 1.0.0

**Comment by Tkko** [comment]
Hey @brvm, try to set `CustomScrollView's` `key` property:

`key: PageStorageKey('scroll_key'),`

**Comment by brvm** [comment]
@Tkko oh wow, that works, thanks! Solved! Didn't know about it's existence.
